on: pull_request
jobs:
 linux:
    uses: minecraft-linux/appimage-builder/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher",
            "path": "mcpelauncher-client",
            "ref": ${{ tojson(github.sha) }}
          }
        ]
      suffix: "-sdl3"
      appImageFlags: |-
        -l -DGAMEWINDOW_SYSTEM=SDL3 -l -DSDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS=1
 macOS:
    uses: minecraft-linux/macos-builder/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher",
            "path": "mcpelauncher-client",
            "ref": ${{ tojson(github.sha) }}
          }
        ]
